name: CI Pipeline

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
        with:
          deno-version: v2.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Cypress
        run: npm install -g cypress

      - name: Verify Cypress installation
        run: |
          echo "Cypress Path: $(which cypress)" # Verifica o caminho onde o Cypress está instalado
          echo "Cypress version: $(cypress --version)" # Verifica a versão do Cypress

      - name: Run tests
        run: cypress run
